config/routes.rb
Rails.application.routes.draw do
  resources :passwords, param: :token
  resources :turbidity_to_bods

  if Rails.env.production?
    resources :users, only: [ :create ]
    resources :reviews, only: [ :new ]
  else
    resources :reviews
    resources :users
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  delete "signout", to: "sessions#destroy"

  # Defines the root path route ("/")
  root "home#index"
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  layout "main", only: [ :new ]
  allow_unauthenticated_access except: [ :new ]
  before_action :set_review, only: %i[ show edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
    @review.reviewer_id = Current.user.id
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy!

    respond_to do |format|
      format.html { redirect_to reviews_path, status: :see_other, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.expect(review: [ :reviewer_id, :reviewee_id, :comment, :rating ])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= form_with(model: review, class: "form") do |form| %>

  <% if review.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>
      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form__field">
    <%= form.label :reviewee_id, "レビューするお店", class: "form__label" %>
    <%= form.text_field :reviewee_id, class: "form__input" %>
  </div>

  <div class="form__field">
    <span class="form__label">評価</span>
    <div class="form__review--stars">
      <% 5.downto(1) do |i| %>
        <%= form.radio_button :rating, i, id: "star#{i}", class: "star-radio" %>
        <%= form.label :rating, for: "star#{i}", class: "star-label" do %>
          <svg><use href="#star"></use></svg>
        <% end %>
      <% end %>
    </div>
  </div>

  <div class="form__field">
    <%= form.label :comment, "コメント", class: "form__label" %>
    <%= form.text_area :comment, class: "form__input" %>
  </div>

  <%= form.submit "送信", class: "form__submit-btn" %>

<% end %>

app/views/reviews/_review.html.erb
<div id="<%= dom_id review %>">
  <p>
    <strong>Reviewer:</strong>
    <%= review.reviewer_id %>
  </p>

  <p>
    <strong>Reviewee:</strong>
    <%= review.reviewee_id %>
  </p>

  <p>
    <strong>Comment:</strong>
    <%= review.comment %>
  </p>

  <p>
    <strong>Rating:</strong>
    <%= review.rating %>
  </p>

</div>

app/views/reviews/_star_svg_sprites.html.erb
<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
  <symbol id="star" viewBox="0 0 24 24">
    <path d="m12 17.275l-4.15 2.5q-.275.175-.575.15t-.525-.2t-.35-.437t-.05-.588l1.1-4.725L3.775 10.8q-.25-.225-.312-.513t.037-.562t.3-.45t.55-.225l4.85-.425l1.875-4.45q.125-.3.388-.45t.537-.15t.537.15t.388.45l1.875 4.45l4.85.425q.35.05.55.225t.3.45t.038.563t-.313.512l-3.675 3.175l1.1 4.725q.075.325-.05.588t-.35.437t-.525.2t-.575-.15z"/>
  </symbol>
</svg>

app/views/reviews/edit.html.erb
<% content_for :title, "Editing review" %>

<h1>Editing review</h1>

<%= render "form", review: @review %>

<br>

<div>
  <%= link_to "Show this review", @review %> |
  <%= link_to "Back to reviews", reviews_path %>
</div>

app/views/reviews/index.html.erb
<p style="color: green"><%= notice %></p>
<% content_for :title, "Reviews" %>
<h1>Reviews</h1>
<div id="reviews">
  <% @reviews.each do |review| %>
    <%= render review %>
    <p>
      <%= link_to "Show this review", review %>
    </p>
  <% end %>
</div>
<%= link_to "New review", new_review_path %>

app/views/reviews/new.html.erb
<% content_for :title, "レビューを書く" %>
<%= render 'star_svg_sprites' %>
<div class="form-wrapper">
  <div class="form-wrapper__container">
    <h1 class="form-wrapper__title">レビューを書く</h1>
    <%= render "form", review: @review %>
    <div class="form-wrapper__links">
      <%= link_to "前のページに戻る",
        (request.referer&.start_with?(request.base_url) ? request.referer : root_path),
        class: "form-wrapper__link" 
      %>
      <%# link_to "レビュー一覧に戻る", reviews_path, class: "form-wrapper__link" %>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @review %>

<div>
  <%= link_to "Edit this review", edit_review_path(@review) %> |
  <%= link_to "Back to reviews", reviews_path %>

  <%= button_to "Destroy this review", @review, method: :delete %>
</div>