config/routes.rb
Rails.application.routes.draw do
  resources :passwords, param: :token
  resources :turbidity_to_bods

  if Rails.env.production?
    resources :users, only: [ :create ]
    resources :reviews, only: [ :new ]
  else
    resources :reviews
    resources :users
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  get "signup", to: "users#new"
  get "signin", to: "sessions#new"
  post "signin", to: "sessions#create"
  delete "signout", to: "sessions#destroy"

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "UNDO" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/main.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "UNDO" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= yield :head %>
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "main", "data-turbo-track": "reload" %>
    <meta name="google-maps-api-key" content="<%= Rails.application.credentials.dig(:google_cloud, :maps_api_key) %>">
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header class="header__container">
      <%= image_tag "logo.png", class: "header__logo", alt: "UNDO Logo" %>
      <div class="header__right">
        <% if authenticated? %>
          <div class="header__user">ログイン中: <%= Current.session.user.email %></div>
          <%= button_to signout_path, class: "header__button", method: :delete do %>
            <%= image_tag "logout-btn.png", height: 50, alt: "ログアウト" %>
          <% end %>
        <% else %>
          <%= link_to "ログイン", signin_path, class: "header__btn--text" %>
        <% end %>
      </div>
    </div>
  </header>
  <main>
    <%= yield %>
  </main>
  <footer>
    <%# TODO: リンクを修正 %>
    <%= button_to "#" do %>
      <%= image_tag "search-btn.png", height: 50, alt: "検索" %>
    <% end %>
    <%= button_to turbidity_to_bods_path do %>
      <%= image_tag "estimate-btn.png", height: 50, alt: "水質推定" %>
    <% end %>
    <button type="button" 
      data-controller="foodshare"
      data-action="click->foodshare#foodshareChange"
      data-foodshare-active-url-value="<%= asset_path("foodshare_start-btn.png") %>" 
      data-foodshare-inactive-url-value="<%= asset_path("foodshare_end-btn.png") %>"
      >
      <%= image_tag "foodshare_start-btn.png", 
                height: 50, 
                data: {foodshare_target: "icon" }
                %>
    </button>
    <%= button_to "#" do %>
      <%= image_tag "settings-btn.png", height: 50, alt: "設定" %>
    <% end %>
  </footer>
</body>
</html>